FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build-env
WORKDIR /app

# copy everything else and build
COPY . ./
RUN dotnet restore 
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1
WORKDIR /app
COPY --from=build-env /app/out .

ENV ASPNETCORE_ENVIRONMENT="Production"

ENV ASPNETCORE_HTTPS_PORT=443

ENTRYPOINT ["dotnet", "TicTacToe.dll"]